name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Push
        run: |
          git config --global user.email "<>"
          git config --global user.name "Build Bot"
          git add download/ -f
          git add upload/ -f
          git commit -m "Build ${{ github.event.head_commit.message }}" || echo "Skipping commit"
          git push
