name: Check Format
on: [push, pull_request]
jobs:
  code-format:
    runs-on: ubuntu-latest
    name: Check Format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Check Format
        run: npm run check-format
