name: Check Format
on: [push, pull_request]
jobs:
  code-format:
    runs-on: ubuntu-latest
    name: Check Format
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Check Format
        run: npm run check-format
